#!/bin/bash

# Get arguments from commend-line
APP_CONFIG=$1
NUM_NODES=$2
EXP_TITLE=$3
SCHEME=$4

DIR_PREFIX=$HOME"/exp/ns-3"
DIR_NAME=$NUM_NODES"nodes_"$APP_CONFIG
FILE_PREFIXES="flowinfo_ flowlog_ ovinfo_ ovlog_ nodelog_ output $APP_CONFIG temp_ newtemp_ res_"

TARGET=$DIR_PREFIX"/"$EXP_TITLE"/"$SCHEME"/"$DIR_NAME
mkdir $TARGET

#
# Copy my own result files
#
for filePrefix in $FILE_PREFIXES;
do
	cp $filePrefix* $TARGET
done

#
# Copy pcap and NetAnim files generated by ns-3
#
cp *.pcap $TARGET
cp *.xml $TARGET

#
# Copy stat files
#
cp nodestat*.txt $TARGET
