#!/bin/bash

# Get arguments from commend-line
APP_CONFIG=$1
NUM_NODES=$2
EXP_TITLE=$3
SCHEME=$4

DIR_PREFIX=$HOME"/exp/ns-3"
DIR_NAME=$NUM_NODES"nodes_"$APP_CONFIG
APPCONFIG_DIR='./apps_config'
FILE_PREFIXES="applog_ flowinfo_ flowlog_ flow_goodput srcrtlog ovinfo_ ovlog_ ovstat_ nodelog_ nodestat output $APPCONFIG_DIR/$APP_CONFIG temp_ rt_mtnc_stat"

TARGET=$DIR_PREFIX"/"$EXP_TITLE"/"$SCHEME"/"$DIR_NAME
mkdir $TARGET

#
# Copy my own result files
#
for filePrefix in $FILE_PREFIXES
do
	cp $filePrefix* $TARGET
done

#
# Copy pcap and NetAnim files generated by ns-3
#
cp *.pcap $TARGET 2> /dev/null
cp *.xml $TARGET 2> /dev/null
